name: Go installation check (fail)
on:
  workflow_dispatch:

jobs:
  check:
    strategy:
      matrix:
        os:
          # - macos-14-large
          # - macos-13-xlarge
          - macos-14
          - macos-13
      
    runs-on: ${{ matrix.os }}

    steps:
    - run: go version
